name: Deploy Legacy Secrets Example

on:
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    uses: revisium/revisium-actions/.github/workflows/deploy.yml@v0.3.3
    with:
      ref: ${{ github.sha }}
      environment: development
      deployment_description: Deploy to Kubernetes
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
      KUBE_SERVICE_NAME: ${{ secrets.KUBE_SERVICE_NAME }}
      KUBE_APP_URL: ${{ secrets.KUBE_APP_URL }}
