name: Docker Build Example

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release/**
    tags:
      - v*

permissions:
  contents: read

jobs:
  build:
    uses: revisium/revisium-actions/.github/workflows/docker-build.yml@v0.3.1
    with:
      image_name: ${{ github.event.repository.name }}
      context: .
      dockerfile: Dockerfile
      emit_latest_tag: true
    secrets: inherit
