name: npm Publish Example

on:
  push:
    tags:
      - v*

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    uses: revisium/revisium-actions/.github/workflows/npm-publish.yml@v0.3.1
    with:
      node_version: 24.11.1
      working_directory: .
      package_path: package.json
      install_command: npm ci
      pre_publish_commands: |
        npm run build
      create_github_release: true
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
